In [3]:
# INPUT BASED OPERATION OF 2 FIXED ARRAYS
import numpy as np
def add(a1,a2):
    return(a1 + a2)
def sub(a1,a2):
    return(a1 - a2)
def mul(a1,a2):
    return(a1 * a2)
def div(a1,a2):
    return(a1 / a2)

a1 = np.array([[1,2,3],[4,5,6]])
a2 = np.array([[7,8,9],[10,11,12]])
choice = input("Enter operation( +, -, *, / ) \n")
if choice == "+":
    print(add(a1,a2))
elif choice == "-":
    print(sub(a1,a2))
elif choice == "*":
    print(mul(a1,a2))
elif choice == "/":
    print(div(a1,a2))    
else:    
    print("Invalid Input.")

Enter operation( +, -, *, / ) 
 -


[[-6 -6 -6]
 [-6 -6 -6]]


In [4]:
# ADDITION OF 2 ARRAYS
a1 = np.array([[1,2,3],[4,5,6]])
a2 = np.array([[7,8,9],[10,11,12]])
a3 = a1 + a2
print(a3)

[[ 8 10 12]
 [14 16 18]]
